# Generated by Django 4.2.7 on 2025-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('category', models.CharField(choices=[('general', 'Общие вопросы'), ('services', 'Услуги'), ('payment', 'Оплата'), ('warranty', 'Гарантия'), ('delivery', 'Доставка'), ('technical', 'Технические вопросы')], default='general', max_length=100, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ['category', 'order', 'date_added'],
            },
        ),
    ]
