# Generated by Django 4.2.7 on 2025-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('salary_min', models.PositiveIntegerField(help_text='В рублях', verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(help_text='В рублях', verbose_name='Зарплата до')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('contract', 'Контракт'), ('internship', 'Стажировка')], default='full_time', max_length=20, verbose_name='Тип занятости')),
                ('experience', models.CharField(choices=[('no_experience', 'Без опыта'), ('1_year', '1 год'), ('2_3_years', '2-3 года'), ('3_5_years', '3-5 лет'), ('5_plus_years', 'Более 5 лет')], default='no_experience', max_length=20, verbose_name='Требуемый опыт')),
                ('location', models.CharField(default='Москва', max_length=200, verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-date_posted'],
            },
        ),
    ]
