# Generated by Django 4.2.7 on 2025-05-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая сумма'),
        ),
    ]
