
-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 23:13:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE USER 'root'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema backend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema backend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `backend` DEFAULT CHARACTER SET utf8 ;
USE `backend` ;

-- -----------------------------------------------------
-- Table `backend`.`user`
-- -----------------------------------------------------
CREATE TABLE `backend`.`user` (
                                                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                `login` VARCHAR(50) NULL,
    `email` VARCHAR(225) NULL,
    `password` VARCHAR(300) NULL,
    `status` ENUM("TestMachine", "Participant", "Coach", "Admin") NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend`.`contest` (
                                                   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                   `contest_name` VARCHAR(50) NULL,
    `start_time` DATETIME NULL,
    `duration` INT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`problem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend`.`problem` (
                                                   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                   `testset` LONGBLOB NOT NULL,
                                                   `checker` BLOB NOT NULL,
                                                   `problem_properties` BLOB NOT NULL,
                                                   `contest_id` INT UNSIGNED NOT NULL,
                                                   PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_problem_contest_idx` (`contest_id` ASC) VISIBLE,
    CONSTRAINT `fk_problem_contest`
    FOREIGN KEY (`contest_id`)
    REFERENCES `backend`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend`.`submission` (
                                                      `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      `solution` BLOB NOT NULL,
                                                      `submit_time` DATETIME NOT NULL,
                                                      `verdict` BLOB NULL,
                                                      `problem_id` INT UNSIGNED NOT NULL,
                                                      `user_id` INT UNSIGNED NOT NULL,
                                                      PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_submission_problem1_idx` (`problem_id` ASC) VISIBLE,
    INDEX `fk_submission_user1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_submission_problem1`
    FOREIGN KEY (`problem_id`)
    REFERENCES `backend`.`problem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_submission_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `backend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`contestAuthor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend`.`contestAuthor` (
                                                         `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                         `user_id` INT UNSIGNED NOT NULL,
                                                         `contest_id` INT UNSIGNED NOT NULL,
                                                         PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_contestAuthor_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_contestAuthor_contest1_idx` (`contest_id` ASC) VISIBLE,
    CONSTRAINT `fk_contestAuthor_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `backend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_contestAuthor_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `backend`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`userProblemResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend`.`userProblemResult` (
                                                             `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                             `result` TINYINT NOT NULL,
                                                             `attempts_count` INT NOT NULL,
                                                             `last_attempt` DATETIME NULL,
                                                             `user_id` INT UNSIGNED NOT NULL,
                                                             `problem_id` INT UNSIGNED NOT NULL,
                                                             PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_userProblemResult_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_userProblemResult_problem1_idx` (`problem_id` ASC) VISIBLE,
    CONSTRAINT `fk_userProblemResult_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `backend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_userProblemResult_problem1`
    FOREIGN KEY (`problem_id`)
    REFERENCES `backend`.`problem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`contestResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend`.`contestResult` (
                                                         `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                         `solvedTasks` INT NOT NULL,
                                                         `penalty` INT NOT NULL,
                                                         `user_id` INT UNSIGNED NOT NULL,
                                                         `contest_id` INT UNSIGNED NOT NULL,
                                                         PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_contestResult_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_contestResult_contest1_idx` (`contest_id` ASC) VISIBLE,
    CONSTRAINT `fk_contestResult_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `backend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_contestResult_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `backend`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`testingQueue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend`.`testingQueue` (
                                                        `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                        `submission_id` INT UNSIGNED NOT NULL,
                                                        PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_testingQueue_submission1_idx` (`submission_id` ASC) VISIBLE,
    CONSTRAINT `fk_testingQueue_submission1`
    FOREIGN KEY (`submission_id`)
    REFERENCES `backend`.`submission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `user` (`login`, `password`, `email`, `status`) VALUES ('admin', '22df674c179820a70cbbe183be510f2c781edc3b5286c7f40f97fc6c8ee75101', 'admin@gmail.com', '4');
INSERT INTO `user` (`login`, `password`, `email`, `status`) VALUES ('testmachine', '202979ff6105a2c7859b95efb411adc7392e43b6aae92a88d8992aba90fe83f4', 'testmachine@gmail.com', '1');